```{r include=FALSE}
# Run this as a chunk before compiling!
options(markdown.HTML.stylesheet = '../stylesheets/prep2013.css')
options(rstudio.markdownToHTML =
  function(inputFile, outputFile) {     
    require(markdown)
    markdownToHTML(inputFile, outputFile, stylesheet='../stylesheets/prep2013.css')  
  }
)
```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script src="../javascripts/main.js"></script>

### MAA PREP 2013 Workshop
### Modeling: Early and Often in Undergraduate Calculus

Schedule
=================

#### Before the Workshop: Early July 2013

* Browse selectively through the videos [listed here](../Resources/ACM-Calculus-course/index.html) from the Associated Colleges of the Midwest (ACM) Online Course: *[Calculus: A Modeling Approach](http://www.acm.edu/features/feature/426?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+ACMNews+%28Associated+Colleges+of+the+Midwest+-+ACM+News%29)*.  The online aspects of this course are being developed by [Chad Topaz](http://www.chadtopaz.com/) at Macalester College and [Tina Garrett](http://www.stolaf.edu/people/garrettk/) at St. Olaf College, based on the Macalester *Applied Calculus* course and using the `mosaic` package for R.

* The [syllabus for the Macalester *Applied Calculus*](http://test.causeweb.org/wiki/mosaic/index.php/Pub114) course.

* *Start R in Calculus* This is a [PDF copy](../Resources/StartR-kindlepdf-version.pdf) of the book used in the Macalester and ACM calculus courses.  You'll receive a **printed, bound copy** at the workshop.  The PDF file is formatted in a size appropriate for a tablet viewer such as an iPad or Kindle.

* TED talks on teaching math: [Conrad Wolfram](http://www.ted.com/talks/conrad_wolfram_teaching_kids_real_math_with_computers.html), [Dan Meyer](http://www.ted.com/talks/dan_meyer_math_curriculum_makeover.html), [Arthur Benjamin](http://www.ted.com/talks/arthur_benjamin_s_formula_for_changing_math_education.html)

* Identifying Modeling Concepts from the MOSAIC kick-off workshop: [video](http://www.ima.umn.edu/videos/?id=1316) and [slides](http://mosaic-web.org/KickOff/Presentations/aspectsOfModeling.pdf)
* A panel discussion on modeling-based calculus with Mariah Birgen, Laurie Heyer, and Joe Mahaffy [video](http://www.mosaic-web.org/MCAST/videos/MCAST-2011-04-29/index.htm) and [slides](http://www.mosaic-web.org/MCAST/materials/April-29-2011/April-29-panel.pdf)

## Monday, July 8, 2013

* Arrival at the College of Idaho in Caldwell, Idaho
    * Shuttle service from the airport
    * Check-in time: 3:00 - 5:00pm
    
* 6:30-9:00 pm  **Welcome dinner** and introductions.
    * Sign up for Thursday evening play: *Much Ado about Nothing*

## Tuesday July 9, 2013

* 7:00-8:00 am Breakfast

#### Session 1


* 11:30-12:30 Lunch

#### Session 2


* 6:00-7:00 Dinner

## Wednesday July 10, 2013

* 7:00-8:00 am Breakfast

#### Session 3


* 11:30-12:30 Lunch

#### Session 4



* 5:30-9:00 Dinner off campus at at [Bitner Vineyards](http://www.bitnervineyards.com/)

## Thursday July 11, 2013

* 7:00-8:00 am Breakfast


#### Session 5


* 11:30-12:30 Lunch

#### Session 6

* 5:30-9:00 Dinner off campus.  [Idaho Shakespeare Festival](http://www.idahoshakespeare.org/) 8pm performance of [*Much Ado about Nothing*](https://en.wikipedia.org/wiki/Much_Ado_About_Nothing)


## Friday July 12, 2013

* 7:00-8:00 am Breakfast

#### Session 7

* 11:30-12:30 Lunch
* 11:30-1:30 Check out
* 1:30 Shuttle service to airport

---------------------------

## Session 1: Tuesday AM

### Software orientation

* Calculus operations in the `mosaic` package. *Start R in Calculus*
* Using R Markdown

### Mathematical functions for modeling
* Deliverable: Slides about your functions

### Fitting parameters
* Examples: Tides, poverty, coffee
   
## Session 2: Tuesday PM

### The process of modeling

* The process of modeling
* Group work on [model settings](model-settings.html)
    
### Working with your current textbook

* Finding "drop-in" activities
* Converting non-modeling activities to modeling activities
* Finding data 
    * coffee and orange juice, prevalence and incidence
    * The Island: Letting Students Experiment and College Data by Michael Bulmer [video](http://www.mosaic-web.org/go/MCAST/videos/MCAST-2012-02-24/index.htm). This is a simulation of realistic demographics, disease, and physiology from which students can collect data for modeling.
* Some bogus models (crickets and beaches)
    
### Tools for Modelers

* Functions in Two Variables
* Residuals

## Session 3 Wednesday AM

### Tools for modelers

* Units and dimensions
* Fitting and precision
* Heuristics for models

## Session 4 Wednesday PM

### Building a case study

* Learning objectives
* Mathematical objectives
* Participant presentations: Your modeling setting

## Session 5 Thursday AM

### Tools for Modelers

* Dynamics
* Optimization
    * [QALYs](http://prep2012.mosaic-web.org/Topics/Optimization/QALY1.html)

## Session 6 Thursday PM

* Building a modeling case study.
* Writing modeling projects and exercises



## Session 7 Friday AM

* The good and bad of open-ended activities
* Participant Presentation: Leading us through a model




