```{r include=FALSE}
# Run this as a chunk before compiling!
options(markdown.HTML.stylesheet = '../stylesheets/prep2013.css')
options(rstudio.markdownToHTML =
  function(inputFile, outputFile) {     
    require(markdown)
    markdownToHTML(inputFile, outputFile, stylesheet='../stylesheets/prep2013.css')  
  }
)
```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script src="../javascripts/main.js"></script>

### MAA PREP 2013 Workshop
### Modeling: Early and Often in Undergraduate Calculus


Session Details
================
## Session 0: Monday Dinner

### Welcome

### Introductions


* [Slides](../Intro/Intro.pdf)
* Participants' [Definitions of Calculus and Modeling](../SessionNotes/definitions.html)


## Session 1: Tuesday AM

### Software orientation

* Orientation to RStudio
* Getting Started with R
  * [The most important template in R](../RIntro/LearningTeachingR.html)
  * Calculus operations in the `mosaic` package. (*[Start R in Calculus](http://www.amazon.com/Start-Calculus-Daniel-T-Kaplan/dp/0983965897)*)
* Using R Markdown

### Mathematical functions for modeling
* Deliverable: Use RMarkdown to defend your choice of functions

### Fitting parameters
* Examples: [world population](../Notes/Functions/WorldPopulation.html), [tides](../Notes/Tides/tides-hawaii.html), [income and housing](https://dl.dropboxusercontent.com/u/5098197/Exercises/HTML/AC-Income-and-Housing/AC-Income-and-Housing-A.html), [cooling water](../Notes/Cooling/CoolingCoffee.html)
   
## Session 2: Tuesday PM

### The process of modeling

* The process of modeling
* Group work on [model settings](model-settings.html)


## Session 3 Wednesday AM

### Review of functions and the modeling process

* Functions for a modeler's toolkit: constant, power-law, exponential, sine, bump, and S-functions.  Linear combinations.
* Fitting and precision
* A [quiz on functions](http://rpubs.com/dtkaplan/792)
* Some other quizzes [1](https://www.dropbox.com/s/14uah8abemevxlw/Quiz-2012-02-03.pdf), [2](https://www.dropbox.com/s/or3p7q1lx0t5o95/Quiz-2012-02-10.pdf), [3](https://www.dropbox.com/s/igvcdbx6553se6f/Quiz-2012-02-17.pdf), [4](https://www.dropbox.com/s/9iya2nozi7szc0h/Quiz-2012-02-24.pdf), [5](https://www.dropbox.com/s/qfa3nwnovsaw5lm/quiz-2012-03-23.pdf), [6](https://www.dropbox.com/s/t8gqptxrfkshxcb/quiz-2012-03-30.pdf), [7](https://www.dropbox.com/s/dcagvob75yicf8h/quiz-2012-04-06.pdf), [8](https://www.dropbox.com/s/zpz5c7y92e4pew2/quiz-2012-04-23.pdf), [mid-term](https://www.dropbox.com/s/t0xeo2yb89jt06m/Mid-Term-March-2012.pdf), [final](https://www.dropbox.com/s/ijgjfw24e54ql2c/Final-May-2012.pdf)
* Markdown and latex: [html](../Resources/latex-rmd.html) and [pdf](../Resources/latex-rmd.pdf), [Rmd](../Resources/latex-rmd.Rmd) and [Rnw](../Resources/latex-rmd.Rnw)

### Derivatives and Anti-derivatives

General comments on [models, mathematics, and calculus](../Notes/Overviews/Modeling-and-Mathematics.html) and on [teaching derivatives and anti-derivatives](../Notes/Overviews/Derivatives.html)
* From a function to its derivatives: [HIV prevalence and incidence](https://dl.dropboxusercontent.com/u/5098197/Math135/In-Class/hiv-graph.pdf); [economic production](https://dl.dropboxusercontent.com/u/5098197/Math135/In-Class/cobb-douglas-partial-derivatives.pdf); [celebrity divorce](https://dl.dropboxusercontent.com/u/5098197/Math135/In-Class/celebrity-divorce.pdf)
* From a derivative to a function: [distance travelled by a car](https://dl.dropboxusercontent.com/u/5098197/Math135/In-Class/road-capacity-activity.pdf) and [traffic light capacity](../Notes/Integration/Traffic-Light-Capacity.html).  Some other [integration model settings](../Notes/Overviews/Integrals.html)


### Tools for modelers

* Residuals -- looking at the cooling water: `fetchData("PREP/water-cooling.csv")`
* Contour Plots
    * [Functions in Two Variables](../Notes/TwoVariables/TwoVariablesIntro.html). 
    * Activity: [Drawing contours](https://dl.dropboxusercontent.com/u/5098197/Math135/In-Class/findingContours.pdf)
    * Activity: the [ideal gas law](https://dl.dropboxusercontent.com/u/5098197/Math135/In-Class/ideal-gas-activity1.pdf)
* Heuristics for polynomials [pdf](http://dl.dropbox.com/u/5098197/Math135/In-Class/poly2d.pdf) and [comments to instructors](../Notes/Polynomials/notes-on-polynomials.html)
* Transformations.  Example: `used-hondas.csv`


## Session 4 Wednesday PM


* Units and dimensions


### Working with your current textbook

* Finding "drop-in" modeling activities
* Converting non-modeling activities to modeling activities
* Finding data 
    * [pouring orange juice](../Notes/OrangeJuiceFlow/OrangeJuice.html), cell telephone sensor data
    * The Island: Letting Students Experiment and College Data by Michael Bulmer [video](http://www.mosaic-web.org/go/MCAST/videos/MCAST-2012-02-24/index.htm). This is a simulation of realistic demographics, disease, and physiology from which students can collect data for modeling.
* Some bogus models: [Snowy Tree crickets](../Notes/Functions/SnowTreeCricket.html) and [beach crowds](../Notes/Optimization/beach-population.html)

### Building a case study

* Learning objectives
* Mathematical objectives
* Participant presentations: Your modeling setting

## Session 5 Thursday AM

### Tools for Modelers

* Dynamics
* Optimization
    * [QALYs](http://prep2012.mosaic-web.org/Topics/Optimization/QALY1.html)

## Session 6 Thursday PM

* Building a modeling case study.
* Writing modeling projects and exercises


## Session 7 Friday AM

* The good and bad of open-ended activities
* Participant Presentation: Leading us through a model

