<style type="text/css">
body {
  box-sizing: border-box;
  font-size: 16px;
  font-family: 'Myriad Pro', Calibri, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  -webkit-font-smoothing: antialiased;
}

h1, h2, h3, h4, h5, h6 {
  margin: 10px 0;
  font-weight: 700;
  color:#222222;
  font-family: 'Lucida Grande', 'Calibri', Helvetica, Arial, sans-serif;
  letter-spacing: -1px;
}

h1 {
  font-size: 36px;
  font-weight: 700;
}

h2 {
  padding-bottom: 10px;
  font-size: 32px;
  background: url('../images/bg_hr.png') repeat-x bottom;
}

h3 {
  font-size: 24px;
}

h4 {
  font-size: 21px;
}

h5 {
  font-size: 18px;
}

h6 {
  font-size: 16px;
}

p {
  margin: 10px 0 15px 0;
}
</style>

Topics
=======================


### MAA PREP 2013
### Modeling: Early and Often in Undergraduate Calculus

## Before the Workshop

This workshop is about using mathematical modeling as a setting in which to introduce students to calculus and motivating calculus for students by the ways it simplifies constructing models of diverse phenomena.

In the weeks leading up to the workshop, we ask you to spend a couple of hours getting oriented.

* Teaching Modeling-Based Calculus --- a brief introduction to a philosophy of modeling-based calculus. (To be posted.)
* Computation and graphics.  You may already have experience teaching with a mathematical software system such as Mathematica, MATLAB, Maple, or Sage.  If so, you likely want to continue using that system. In order to provide a common framework for the workshop, and in order to guarantee that all participants have a computational platform that they can bring back to their own institution, we'll be using the free and open-source R with the RStudio and the `mosaic` package.  Upon registration, all participants will receive a free copy of ["Start R in Calculus"](http://www.amazon.com/Start-Calculus-Daniel-T-Kaplan/dp/0983965897/ref=sr_1_1?ie=UTF8&qid=1366313996&sr=8-1&keywords=start+r+in+calculus).  We'll also set you up with an account on a web-based RStudio server.  

You'll notice that the topics for the workshop are not in the order you would use in your own classes. Unlike your students, you already know the operations and concepts of calculus.  So our first day is about building models, even though some of these use calculus.  Later, we'll introduce some models that motivate topics of calculus, so you can teach calculus in the context of modeling.


Please note: This is a working outline.  The topics and their order may change before the workshop.

```{r, echo=FALSE}
displayFile <- function(path, text=path, type=c('html','Rmd')) {
  result <- paste(text, paste("[[", type, "] ](", path, ".", type, ")", sep="", collapse="" ) )
  return(result)
  }
```

## Monday

### Evening

Welcome dinner and introductions.  Some ice-breaking modeling activities.

## Tuesday

* Functions for modeling and their parameters [link](http://rpubs.com/dtkaplan/584)
    * Examples: Snow Tree Crickets `r I(displayFile('../Notes/Functions/SnowTreeCricket',''))` : World Population `r I(displayFile('../Notes/Functions/WorldPopulation',''))` : Tides in Hawaii `r I(displayFile('../Notes/Tides/tides-hawaii',''))` : Hill Functions `r I(displayFile('../Notes/Functions/hillFunctions',''))`: Cooling Coffee `r I(displayFile('../Notes/Cooling/CoolingCoffee',''))` 

* The contour plot approach to functions of two variables `r I(displayFile('../Notes/TwoVariables/TwoVariablesIntro',''))`

* Polynomials approximation and modeling
    * Examples
        * Straight-line models `r I(displayFile('../Notes/Functions/LinearFunctions',''))`
        * Application in Model Building: Enzyme kinetics Michaelis-Menten dynamics `r I(displayFile('../Notes/Michaelis-Menten/MichaelisMenten',''))` 
        * Notes on polynomials as models. `r I(displayFile('../Notes/Polynomials/notes-on-polynomials',''))` 
        * Selecting model terms from first principles. [pdf](http://dl.dropbox.com/u/5098197/Math135/In-Class/poly2d.pdf)
        * Linear Approximation in Max Heart Rate [pdf](http://dl.dropbox.com/u/5098197/PREP2012/max-hr.pdf)
    * Activities : Eyeballing interactions [pdf](http://dl.dropbox.com/u/5098197/Math135/In-Class/eyeball-partials.pdf) : Celebrity Divorce [pdf](http://dl.dropbox.com/u/5098197/Math135/In-Class/celebrity-divorce.pdf) : A mosaicManip applet for visualizing quadratic approximation in two variables. [pdf](http://dl.dropbox.com/u/5098197/Math135/In-Class/poly2-approx.pdf)

* Modeling heuristics [pdf](http://dl.dropbox.com/u/5098197/Math135/In-Class/poly2d.pdf)


## Wednesday

* Limits `r I(displayFile('../Notes/Limits/notes-on-limits',''))`
* Derivatives and Integrals
    * Examples: Foot Arch `r I(displayFile('../Notes/Functions/footStretch',''))` : Traffic Light Capacity `r I(displayFile('../Notes/Integration/Traffic-Light-Capacity',''))` : Missile Acceleration [pdf](https://dl.dropbox.com/u/5098197/PREP2012/missile-launch.pdf) : Orange Juice `r I(displayFile('../Notes/OrangeJuiceFlow/OrangeJuice',''))` : Lake volume
    * Notes: Function/Derivative Pairs `r I(displayFile('../Notes/Overviews/Derivatives',''))` : `r I(displayFile('../Notes/Overviews/Integrals',''))` 
    * Resources
       * Prevalence and incidence of HIV [link](http://dl.dropbox.com/u/5098197/Math135/In-Class/hiv-graph.pdf)
       * Sommer Gentry's (USNA) exercise on [derivatives and the economy](http://www.mosaic-web.org/Repository/SommerGentry/secondDerivativeInTheNews.pdf)
       * The ideal gas law [file link](http://dl.dropbox.com/u/5098197/Math135/In-Class/ideal-gas-activity1.pdf)
       * Modeling projection with Cobb-Douglas `r I(displayFile('../Notes/Cobb-Douglas/cobb-douglas',''))`
       * Related rates as change along a path `r I(displayFile('../Notes/RelatedRates/RelatedRatesIntro',''))`

* Optimization
    * Modeling aspects of optimization `r I(displayFile('../Notes/Optimization/One-Variable-Optimization',''))` including the oil-can example and multiple objectives
    * Examples: Beach Population `r I(displayFile('../Notes/Optimization/beach-population',''))` : Optimization of Quality Adjusted Life Years `r I(displayFile('../Notes/Optimization/QALY1',''))` : Toronto Ball `r I(displayFile('../Notes/Functions/Toronto-Ball',''))` : Do Dogs Know Calculus? [pdf of MAA article](http://www.maa.org/features/elvisdog.pdf) and Dog Calculus is Economics `r I(displayFile('../Notes/Optimization/Dog-Calculus',''))` : 

* Modeling with Series `r I(displayFile('../Notes/Series/notes-on-series',''))`

## Thursday

* Dynamics
    * Mechanics and what not to do: Solving the Logistic DE, the AP Exam problem `r I(displayFile('../Notes/DiffEQ/AlgebraAndIntroDE',''))`
    * Dynamical phenomena
    * Differential equations as a framework for modeling
        * A rowing problem `r I(displayFile('../Notes/DiffEQ/RowingProblem',''))`
        * Love and war

## Friday

### Morning

