bb = fetchData()
xyplot(y ~ t, data=b)
xyplot(y ~ t, data=bb)
xyplot(y ~ t, data=b,add=TRUE, col="red")
plotPoints(y ~ t, data=b,add=TRUE, col="red")
xyplot(y ~ t, data=bb)
plotPoints(y ~ t, data=b,add=TRUE, col="red")
h = fetchData("used-hondas.csv")
names(h)
xyplot( Price ~ Mileage, data=h)
xyplot( log(Price) ~ Mileage, data=h)
xyplot( log(Price) ~ Age, data=h)
xyplot( Price ~ Age, data=h)
pricesOfHondas <- fetchData("used-hondas.csv")
names(pricesOfHondas)
xyplot(Price ~ Mileage, data=pricesOfHondas )
xyplot(Price ~ Mileage, data=pricesOfHondas, ylim=c(0,25000) )
xyplot(log10(Price) ~ Mileage, data=pricesOfHondas )
steel = fetchData("PREP/SteelBalls.csv")
head(steel)
xyplot(y ~ t, data=steel)
filters = fetchData("PREP/13AirFilters.csv")
plotPoints(y ~ t, data=filters, add=TRUE, col="red")
plotPoints(y ~ t, data=filters, col="red")
plotPoints(y ~ t, data=steel, col="blue")
plotPoints(y ~ t, data=filters, col="red")
plotPoints(y ~ t, data=steel, col="blue",add=TRUE)
plotPoints(y ~ t, data=steel, col="blue", xlim=c(0,4.2))
plotPoints(y ~ t, data=steel, col="blue", xlim=c(0,.42))
plotPoints(y ~ t, data=steel, col="blue", xlim=c(0,.43))
plotPoints(y ~ t, data=steel, col="blue", xlim=c(0,.45))
plotPoints(y ~ t, data=steel, col="blue", xlim=c(0,.49))
first = subset(steel, t<.45)
plotPoints(y ~ t, data=first, col="blue")
steelHeight = fitModel(y ~ y0+ v0*t + .5*9.8*t^2, data=first)
steelHeight
steelHeight = fitModel(y ~ y0+ v0*t - .5*9.8*t^2, data=first)
steelHeight
plotFun(steelHeight(t)~t, add=TRUE)
steelHeightScrewy = fitModel(y ~ y0+ v0*t + .5*9.8*t^2, data=first)
plotFun(steelHeightScrewy(t)~t, col="red",add=TRUE)
steelHeight2 = fitModel(y ~ y0+ v0*t + .5*g*t^2, data=first)
steelHeight2
steel$resid = steel$y - steelHeight(steel$t)
steel$resid
first = transform(resid = y - steelHeight(t))
first = transform(first,resid = y - steelHeight(t))
head(first)
first$resid
mean(resid, data=first)
mean(resid^2, data=first)
sqrt(9e-6)
first = transform(first, newy = y + rnorm(14,0,.003))
rnorm(14,0,.003)
rnorm(14,0,.003)
rnorm(14,0,.003)
steelHeight2 = fitModel(newy ~ y0+ v0*t + .5*g*t^2, data=first)
steelHeight2
steelHeight2 = fitModel(y ~ y0+ v0*t + .5*g*t^2, data=resample(first))
steelHeight2
steelHeight2 = fitModel(y ~ y0+ v0*t + .5*g*t^2, data=resample(first))
steelHeight2
steelHeight2 = fitModel(y ~ y0+ v0*t + .5*g*t^2, data=resample(first))
steelHeight2
points = 1:4
points
resample(points)
resample(first)
xyplot(y~t, data=filters)
terminal = subset(filters, t>.5)
steelHeight = fitModel(y ~ y0+ v0*t - .5*g*t^2, data=terminal)
filterHeight = fitModel(y ~ y0+ v0*t - .5*g*t^2, data=terminal)
filterHeight
coef(filterHeight)
xyplot(y~t, data=terminal)
plotFun(filterHeight(t)~t, add=TRUE)
filterHeight = fitModel(y ~ y0+ v0*t - .5*g*t^2, data=resample(terminal))
filterHeight = fitModel(y ~ y0+ v0*t - .5*g*t^2, data=resample(terminal))
filterHeight = fitModel(y ~ y0+ v0*t - .5*g*t^2, data=terminal)
filterHeight2 = fitModel(y ~ y0+ v0*t, data=terminal)
mLM( wage ~ sex+age+sector, data=CPS85)
mod = lm( y ~ t + I(t^2), data=first)
mod
anova(mod)
anova(mod)
summary(mod)
mod = lm( y ~ t + I(t^2), data=terminal)
anova(mod
)
summary(mod)
mod = lm( y ~ t , data=terminal)
summary(mod)
f = rfun(~x&y, seed=42065)
plotFun(f(x,y)~x&y, x.lim=c(-5,5),y.lim=c(-5,5))
5 + 3
plotFun(3 + 4*x - 5*y~x&y, x.lim=c(-5,5),y.lim=c(-5,5))
plotFun(3 + 4*x - 5*y + 2*x*y~x&y, x.lim=c(-5,5),y.lim=c(-5,5))
plotFun(3 + 4*x - 5*y + 1*x*y~x&y, x.lim=c(-5,5),y.lim=c(-5,5))
plotFun(3 + 4*x - 5*y + 2*x*y~x&y, x.lim=c(-5,5),y.lim=c(-5,5))
plotFun(3 + 4*x - 5*y + 1*x*y~x&y, x.lim=c(-5,5),y.lim=c(-5,5))
plotFun(f(x,y)~x&y, x.lim=c(-5,5),y.lim=c(-5,5))
dfdx <- D(f(x,y)~ x)
plotFun(dfdx(x,y)~x&y, x.lim=c(-5,5),y.lim=c(-5,5))
dfdxdy <- D(f(x,y)~ x&y)
plotFun(dfdxdy(x,y)~x&y, x.lim=c(-5,5),y.lim=c(-5,5))
dfdxdy2 <- D(f(x,y)~ y&x)
plotFun(dfdxdy(x,y)-dfdxdy2(x,y)~x&y, x.lim=c(-5,5),y.lim=c(-5,5))
dfdxdy(3,2)
dfdxdy2(3,2)
dfdxdy2(x=3,y=2)
