Traffic light capacity model
==========================
```{r echo=FALSE,message=FALSE,warning=FALSE,error=FALSE,results="hide",label="options"}
require(knitr, quietly=TRUE)
opts_chunk$set(fig.width=5,fig.height=5,out.width="5in")
library(mosaic,quietly=TRUE)
trellis.par.set(theme=col.mosaic())
```

Your task: Find the capacity of a traffic light.

### Methodological hint: 
The worst case is a line of cars is standing still at the light when it turns green.  Cars accelerate.  The last car to get through the light is at braking distance from the light when it turns yellow.

### What are the parameters of the system?
* Duty cycle for the light.
* Speed limit for the road.

### What estimates do you need to make? 
* Distance between stopped cars, length of cars, etc.  
* Lag time between movement of car in front and the car in question.
* How far a car can move during the green-light phase.

### How far does the car go?

Starting from a dead stop and accelerating up to the speed limit, how far will a car travel at time $t$?

Some sources for information about car performance: [1](http://www.albeedigital.com/supercoupe/articles/0-60times.html), [2](http://www.0-60times.com/)

You may need to translate this information into a form suitable for your calculation.

### Sensitivity and Uncertainty

What’s the sensitivity of the result to the various assumptions?  How much uncertainty is there in your guesses about the values of variables?  What’s the first thing you would collect some data about?


